# Data Analysis - Read Data

Oliver Zott / 
08.07.2019

- read data
- process data
- store in new csv with specific formatting

In [38]:
# Packages
import pandas as pd

**1. Read Data: skip first 10 rows / specify delimiter**

In [39]:
# relatove path (subfolder: "data")
test = pd.read_csv('data/smhi-opendata_5_53540_20190617_233641.csv', skiprows = range(0,10), sep = ';')
test.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Nederbördsmängd,Kvalitet,Unnamed: 5,Tidsutsnitt:
0,01.02.1957 06:00,02.02.1957 06:00,01.02.1957,0.0,G,NaN,Kvalitetskontrollerade historiska data (utom d...
1,02.02.1957 06:00,03.02.1957 06:00,02.02.1957,0.0,G,NaN,Tidsperiod (fr.o.m.) = 1957-02-01 00:00:00 (UTC)
2,03.02.1957 06:00,04.02.1957 06:00,03.02.1957,0.0,G,NaN,Tidsperiod (t.o.m.) = 2019-03-01 06:00:00 (UTC)
3,04.02.1957 06:00,05.02.1957 06:00,04.02.1957,0.0,G,NaN,Värdet är summerat över = 24 timmar
4,05.02.1957 06:00,06.02.1957 06:00,05.02.1957,0.0,G,NaN,NaN

**2. Chose own column-labels**

In [40]:
df_raw = pd.read_csv('data/smhi-opendata_5_53540_20190617_233641.csv', skiprows = range(0,11), sep = ';', 
                names = ['From (Date/Time)', 'Till (Date/Time)', 'Representative Day', 'Rainfall', 
                         'Quality', 'unknown1', 'unknown2'])
df_raw.head()

,From (Date/Time),Till (Date/Time),Representative Day,Rainfall,Quality,unknown1,unknown2
0,01.02.1957 06:00,02.02.1957 06:00,01.02.1957,0.0,G,NaN,Kvalitetskontrollerade historiska data (utom d...
1,02.02.1957 06:00,03.02.1957 06:00,02.02.1957,0.0,G,NaN,Tidsperiod (fr.o.m.) = 1957-02-01 00:00:00 (UTC)
2,03.02.1957 06:00,04.02.1957 06:00,03.02.1957,0.0,G,NaN,Tidsperiod (t.o.m.) = 2019-03-01 06:00:00 (UTC)
3,04.02.1957 06:00,05.02.1957 06:00,04.02.1957,0.0,G,NaN,Värdet är summerat över = 24 timmar
4,05.02.1957 06:00,06.02.1957 06:00,05.02.1957,0.0,G,NaN,NaN

**3. Store Date in new csv-file**

In [41]:
df_raw.to_csv('rainfall_Stehag.csv', index = False, columns = ['From (Date/Time)', 'Till (Date/Time)', 'Representative Day',
                                           'Rainfall', 'Quality'])

df = pd.read_csv('rainfall_Stehag.csv')
df

       From (Date/Time)  Till (Date/Time) Representative Day Rainfall Quality
0      01.02.1957 06:00  02.02.1957 06:00         01.02.1957      0.0       G
1      02.02.1957 06:00  03.02.1957 06:00         02.02.1957      0.0       G
2      03.02.1957 06:00  04.02.1957 06:00         03.02.1957      0.0       G
3      04.02.1957 06:00  05.02.1957 06:00         04.02.1957      0.0       G
4      05.02.1957 06:00  06.02.1957 06:00         05.02.1957      0.0       G
5      06.02.1957 06:00  07.02.1957 06:00         06.02.1957      0.0       G
6      07.02.1957 06:00  08.02.1957 06:00         07.02.1957      0.0       G
7      08.02.1957 06:00  09.02.1957 06:00         08.02.1957      8.0       G
8      09.02.1957 06:00  10.02.1957 06:00         09.02.1957   08.Mär       G
9      10.02.1957 06:00  11.02.1957 06:00         10.02.1957      0.0       G
10     11.02.1957 06:00  12.02.1957 06:00         11.02.1957      0.1       G
11     12.02.1957 06:00  13.02.1957 06:00         12.02.1957   09.Mai       G
12     13.02.1957 06:00  14.02.1957 06:00         13.02.1957   04.Mai       G
13     14.02.1957 06:00  15.02.1957 06:00         14.02.1957      6.0       G
14     15.02.1957 06:00  16.02.1957 06:00         15.02.1957      0.0       G
15     16.02.1957 06:00  17.02.1957 06:00         16.02.1957      8.0       G
16     17.02.1957 06:00  18.02.1957 06:00         17.02.1957      0.0       G
17     18.02.1957 06:00  19.02.1957 06:00         18.02.1957   02.Mai       G
18     19.02.1957 06:00  20.02.1957 06:00         19.02.1957      0.5       G
19     20.02.1957 06:00  21.02.1957 06:00         20.02.1957      1.0       G
20     21.02.1957 06:00  22.02.1957 06:00         21.02.1957   01.Jän       G
21     22.02.1957 06:00  23.02.1957 06:00         22.02.1957   06.Mai       G
22     23.02.1957 06:00  24.02.1957 06:00         23.02.1957      1.0       G
23     24.02.1957 06:00  25.02.1957 06:00         24.02.1957      0.0       G
24     25.02.1957 06:00  26.02.1957 06:00         25.02.1957      0.0       G
25     26.02.1957 06:00  27.02.1957 06:00         26.02.1957      0.0       G
26     27.02.1957 06:00  28.02.1957 06:00         27.02.1957      0.5       G
27     28.02.1957 06:00  01.03.1957 06:00         28.02.1957      0.0       G
28     01.03.1957 06:00  02.03.1957 06:00         01.03.1957      0.0       G
29     02.03.1957 06:00  03.03.1957 06:00         02.03.1957      0.0       G
...                 ...               ...                ...      ...     ...
22551  30.01.2019 06:00  31.01.2019 06:00         30.01.2019      0.0       G
22552  31.01.2019 06:00  01.02.2019 06:00         31.01.2019      0.0       G
22553  01.02.2019 06:00  02.02.2019 06:00         01.02.2019      0.0       G
22554  02.02.2019 06:00  03.02.2019 06:00         02.02.2019   03.Jän       G
22555  03.02.2019 06:00  04.02.2019 06:00         03.02.2019      0.0       G
22556  04.02.2019 06:00  05.02.2019 06:00         04.02.2019   02.Aug       G
22557  05.02.2019 06:00  06.02.2019 06:00         05.02.2019   01.Sep       G
22558  06.02.2019 06:00  07.02.2019 06:00         06.02.2019   04.Jul       G
22559  07.02.2019 06:00  08.02.2019 06:00         07.02.2019   04.Jun       G
22560  08.02.2019 06:00  09.02.2019 06:00         08.02.2019   18.Mai       G
22561  09.02.2019 06:00  10.02.2019 06:00         09.02.2019   03.Mai       G
22562  10.02.2019 06:00  11.02.2019 06:00         10.02.2019   05.Mai       G
22563  11.02.2019 06:00  12.02.2019 06:00         11.02.2019      0.0       G
22564  12.02.2019 06:00  13.02.2019 06:00         12.02.2019      0.7       G
22565  13.02.2019 06:00  14.02.2019 06:00         13.02.2019      0.3       G
22566  14.02.2019 06:00  15.02.2019 06:00         14.02.2019      0.0       G
22567  15.02.2019 06:00  16.02.2019 06:00         15.02.2019      0.0       G
22568  16.02.2019 06:00  17.02.2019 06:00         16.02.2019      0.0       G
22569  17.02.2019 06:00  18.02.2019 06:00         17.02.2019      0.0       G
22570  18.02.2019 06:00  19.02.2019 06:00         18.02.2019      0.0       G
22571  19.02.2019 06:00  20.02.2019 06:00         19.02.2019   03.Jun       G
22572  20.02.2019 06:00  21.02.2019 06:00         20.02.2019   05.Apr       G
22573  21.02.2019 06:00  22.02.2019 06:00         21.02.2019   05.Feb       G
22574  22.02.2019 06:00  23.02.2019 06:00         22.02.2019      0.0       G
22575  23.02.2019 06:00  24.02.2019 06:00         23.02.2019      0.0       G
22576  24.02.2019 06:00  25.02.2019 06:00         24.02.2019      0.0       G
22577  25.02.2019 06:00  26.02.2019 06:00         25.02.2019      0.0       G
22578  26.02.2019 06:00  27.02.2019 06:00         26.02.2019      0.0       G
22579  27.02.2019 06:00  28.02.2019 06:00         27.02.2019      0.0       G
22580  28.02.2019 06:00  01.03.2019 06:00         28.02.2019      0.0       G

[22581 rows x 5 columns]

## Conclusion:

- obviously some error in rainfall column (value interpreted as date)
- next possible step: 
 - plot one specific year (Time series)
 - group and compare years
 - ...